name: Debian Package CI

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:
    branches:
      - branchAutoPackage

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install packaging tools
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool dpkg-dev debhelper

    - name: Build package
      run: |
        ./configure
        make
        make dist
        dpkg-buildpackage -us -uc -b
