name: Autotools Build CI

on:
  push:
    branches:
      - branchAutomake
  pull_request:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Generate configure script
      run: autoreconf --install

    - name: Run configure
      run: ./configure

    - name: Build the project
      run: make

    - name: Create tarball
      run: make dist
